### ISSUE TITLE
본인 질문 삭제 기능 및 엔터키 동작 구현 변경

### ISSUE THREAD

**Issue by zzJinux** [itsnamgyu/gugugu#15]
엔터가 개행인 줄 알고 눌렀다가 질문이 등록됐는데 삭제를 못하는 상황이 이따금씩 보이네요.

**Comment by itsnamgyu** [comment]
2934e81 해결했습니다! 엔터를 치면 개행이 되고, ctrl/alt/shift와 함깨 누르면 질문 등록이 되는 방식으로 수정했습니다.

피드백 감사합니다!
