### ISSUE TITLE
로고가 클릭은 되지만 아무 일도 일어나지 않습니다

### ISSUE THREAD

**Issue by fuzzythecat** [itsnamgyu/gugugu#3]
![image](https://user-images.githubusercontent.com/12467657/52544801-76cf1b80-2df6-11e9-8ab2-40c5c1123c22.png)

방 안에서 좌측 상단의 로고를 클릭했을 때 홈 화면으로 돌아갈 수 있으면 좋겠어요

**Comment by itsnamgyu** [comment]
Resolved 5b388f8

<img width="255" alt="극혐;" src="https://user-images.githubusercontent.com/23400562/52549580-39c75100-2e17-11e9-8cae-3a89e003e4b3.png">

> My apologies...
